CREATE DATABASE IF NOT EXISTS ELETRODOMESTICOS_SAEP_DB;
USE ELETRODOMESTICOS_SAEP_DB;

CREATE TABLE USUARIO (
    USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USU_NOME VARCHAR(250),
    USU_EMAIL VARCHAR(250),
    USU_SENHA VARCHAR(250)
);

CREATE TABLE PRODUTO (
    PROD_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    PROD_NOME VARCHAR(250) NOT NULL,
    PROD_FORNECEDOR VARCHAR(250) NOT NULL,
    PROD_CATEGORIA VARCHAR(250) NOT NULL,
    PROD_QUANTIDADE VARCHAR(250) NOT NULL,
    PROD_GARANTIA VARCHAR(250) NOT NULL,
    FK_USU_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID)
);

CREATE TABLE ESTOQUE (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    QNTDE_ESTOQUE VARCHAR(250) NOT NULL,
    FK_PROD_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_PROD_ID) REFERENCES PRODUTO(PROD_ID)
);

CREATE TABLE LOGS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(250),
    DATA_HORA DATE
);

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES
('Maria','maria@email.com','123456'),
('João','joao@email.com','123456'),
('Clara','clara@email.com','123456');

INSERT INTO PRODUTO (PROD_NOME, PROD_FORNECEDOR, PROD_CATEGORIA, PROD_REPOSICAO, PROD_GARANTIA,FK_USU_ID)
VALUES
('Geladeira','Eletrolux','Cozinha','50','5 anos',1),
('Ar Condicionado','Samsung','Climatização','20','3 anos',2),
('Aspirador de Pó','Mondial','Limpeza','100','6 anos',3);

INSERT INTO ESTOQUE (QNTDE_ESTOQUE, FK_PROD_ID)
VALUES
('100',1),
('50',2),
('250',3);
 